sudo: required
services: docker
language: generic

env:
  - TEST_CASE=1.4
  - TEST_CASE=1.5
  - TEST_CASE=1.6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblz4-tool

script:
  - ./test.sh
